# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # 虚拟机镜像名字，不能改
  config.vm.box_url = "https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/bionic/20181212/bionic-server-cloudimg-amd64-vagrant.box"
  config.vm.box = "ubuntu/bionic"

  # 映射文件夹
  config.vm.synced_folder ".", "/var/www/web21"

  # 桥接网络
  config.vm.network "public_network"

  # 脚本
  config.vm.provision "shell", inline: <<-SHELL
    # 换成 root 用户运行
    sudo su
    bash /var/www/web21/mirror.sh
    bash /var/www/web21/deploy.sh
  SHELL
  
end
